{
    "type": "bundle",
    "id": "bundle--79cbb136-b226-449d-80cc-62601b28eb0f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--8bc9cc59-bbbc-4618-a06d-25d0c63dbeab",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-05-08T07:21:38.939927Z",
            "modified": "2025-05-08T07:21:38.939927Z",
            "name": "CVE-2025-37816",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nmei: vsc: Fix fortify-panic caused by invalid counted_by() use\n\ngcc 15 honors the __counted_by(len) attribute on vsc_tp_packet.buf[]\nand the vsc-tp.c code is using this in a wrong way. len does not contain\nthe available size in the buffer, it contains the actual packet length\n*without* the crc. So as soon as vsc_tp_xfer() tries to add the crc to\nbuf[] the fortify-panic handler gets triggered:\n\n[   80.842193] memcpy: detected buffer overflow: 4 byte write of buffer size 0\n[   80.842243] WARNING: CPU: 4 PID: 272 at lib/string_helpers.c:1032 __fortify_report+0x45/0x50\n...\n[   80.843175]  __fortify_panic+0x9/0xb\n[   80.843186]  vsc_tp_xfer.cold+0x67/0x67 [mei_vsc_hw]\n[   80.843210]  ? seqcount_lockdep_reader_access.constprop.0+0x82/0x90\n[   80.843229]  ? lockdep_hardirqs_on+0x7c/0x110\n[   80.843250]  mei_vsc_hw_start+0x98/0x120 [mei_vsc]\n[   80.843270]  mei_reset+0x11d/0x420 [mei]\n\nThe easiest fix would be to just drop the counted-by but with the exception\nof the ack buffer in vsc_tp_xfer_helper() which only contains enough room\nfor the packet-header, all other uses of vsc_tp_packet always use a buffer\nof VSC_TP_MAX_XFER_SIZE bytes for the packet.\n\nInstead of just dropping the counted-by, split the vsc_tp_packet struct\ndefinition into a header and a full-packet definition and use a fixed\nsize buf[] in the packet definition, this way fortify-source buffer\noverrun checking still works when enabled.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-37816"
                }
            ]
        }
    ]
}