{
    "type": "bundle",
    "id": "bundle--78232ea7-a320-4b2f-bac5-5dc6460d60b2",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--7f0436ca-bb68-4c51-91d1-48f496887f9f",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-01-19T00:24:27.275982Z",
            "modified": "2022-01-19T00:24:27.275982Z",
            "name": "CVE-2021-4146",
            "description": "Business Logic Errors in GitHub repository pimcore/pimcore prior to 10.2.6.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2021-4146"
                }
            ]
        }
    ]
}