{
    "type": "bundle",
    "id": "bundle--fe9802cf-5732-4dd0-be00-094958210279",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--b4c93ea9-05b9-4c87-b5ed-20f1593f70b3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-01-18T03:17:45.118072Z",
            "modified": "2024-01-18T03:17:45.118072Z",
            "name": "CVE-2023-48359",
            "description": "In autotest driver, there is a possible out of bounds write due to improper input validation. This could lead to local denial of service with System execution privileges needed",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-48359"
                }
            ]
        }
    ]
}