{
    "id": "bundle--de1a7f21-eaf7-49c3-a85e-307199a61dd0",
    "objects": [
        {
            "created": "2021-03-13T20:11:15.389227Z",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "description": "libautotrace.a in AutoTrace 0.31.1 has a \"cannot be represented in type int\" issue in input-tga.c:528:63.",
            "external_references": [
                {
                    "external_id": "CVE-2017-9200",
                    "source_name": "cve"
                }
            ],
            "id": "vulnerability--c6952a32-abdb-4653-a5e8-92e3de53a1d9",
            "modified": "2021-11-22T14:54:52.900149Z",
            "name": "CVE-2017-9200",
            "spec_version": "2.1",
            "type": "vulnerability"
        }
    ],
    "type": "bundle"
}