{
    "type": "bundle",
    "id": "bundle--75f9d37c-4fcd-430f-bc1e-b0171526b14f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--1b8dce0a-7f69-4dfe-ac24-0474aa458713",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-08-23T07:13:45.70685Z",
            "modified": "2023-08-23T07:13:45.70685Z",
            "name": "CVE-2023-41105",
            "description": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-41105"
                }
            ]
        }
    ]
}