{
    "type": "bundle",
    "id": "bundle--8e506a2c-b472-4bcf-8c97-4a03e063e2e4",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--1af2bb75-4788-4237-9757-3e97c419267d",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-02-01T15:15:05.735379Z",
            "modified": "2024-02-01T15:15:05.735379Z",
            "name": "CVE-2024-1141",
            "description": "A vulnerability was found in python-glance-store. The issue occurs when the package logs the access_key for the glance-store when the DEBUG log level is enabled.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-1141"
                }
            ]
        }
    ]
}