{
    "type": "bundle",
    "id": "bundle--f47c207a-e8ef-4858-bd07-d4c728503270",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--a293842b-55e4-4296-b8c4-04d137ed4ec6",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-29T06:22:49.413376Z",
            "modified": "2024-05-29T06:22:49.413376Z",
            "name": "CVE-2023-52794",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nthermal: intel: powerclamp: fix mismatch in get function for max_idle\n\nKASAN reported this\n\n      [ 444.853098] BUG: KASAN: global-out-of-bounds in param_get_int+0x77/0x90\n      [ 444.853111] Read of size 4 at addr ffffffffc16c9220 by task cat/2105\n      ...\n      [ 444.853442] The buggy address belongs to the variable:\n      [ 444.853443] max_idle+0x0/0xffffffffffffcde0 [intel_powerclamp]\n\nThere is a mismatch between the param_get_int and the definition of\nmax_idle.  Replacing param_get_int with param_get_byte resolves this\nissue.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-52794"
                }
            ]
        }
    ]
}